### ISSUE TITLE
Outbound SMTP Auth Support

### ISSUE THREAD

**Issue by MHillyer** [KumoCorp/kumomta#10]

**Comment by wez** [comment]
Game plan:

* Expand our SMTP client to support `AUTH PLAIN`
* Add configuration to https://docs.kumomta.com/reference/kumo/make_egress_path/ to allow:
  * Specifying the username and password using [keysource](https://docs.kumomta.com/reference/keysource/)
  * An option to allow using PLAIN even if TLS is not active. Default would be to only use it when TLS is active on the session.  If TLS is not active but is required, then behave similarly to `enable_tls = "Opportunistic"`: will not try to send on a connection where the settings are mismatched from our expectation
