### ISSUE TITLE
Rewrite Remote Server Responses

### ISSUE THREAD

**Issue by MHillyer** [KumoCorp/kumomta#112]
There are occasions where an MBP will provide a response that is not how the sender would want to classify things.

One example: Gmail will respond for a mailbox full situation with 

`452 4.2.2 The recipient's inbox is out of storage space.`

While Google thinks this is a temporary situation since the user may login at any time and clear out some space, the sender considers this to be fatal for the current given message.

The user needs the ability to write a rule that says a given response should be rewritten, allowing them to make the response:

`552 5.2.2 The recipient's inbox is out of storage space.`

KumoMTA would then process logic against the updated rule, resulting in a permanent failure that would receive a proper bounce classification and any traffic shaping automation rules would apply according to the rewritten rule.

**Comment by wez** [comment]
How is this different from this existing feature?
https://docs.kumomta.com/reference/events/smtp_client_rewrite_delivery_status/

**Comment by MHillyer** [comment]
Closing.
