### ISSUE TITLE
Configure Max Retries

### ISSUE THREAD

**Issue by MHillyer** [KumoCorp/kumomta#14]

**Comment by wez** [comment]
Note that today we support setting the [max_age](https://docs.kumomta.com/reference/kumo/make_queue_config/#max_age) of a message in the queue.

A potential issue with max retries is that exigent circumstances may cause a message to be retried more or less frequently than normal, making it more difficult to reason about the maximum lifetime of any given message if the lifetime was determined solely by the number of retries.

Another tricky aspect of supporting this is that we don't store the precise retry count across a restart (the I/O cost is considered to be too high to record this metadata), and instead infer it based on the creation time of the message and the other queue configuration parameters.  That means that we will only have an approximation of the number of retries known to the responsible kumod instance.

**Comment by wez** [comment]
We decided not to implement this
