### ISSUE TITLE
Provide the ability to immediately retry (re-bind/flush) select messages in the spool

### ISSUE THREAD

**Issue by tommairs** [KumoCorp/kumomta#152]
There should be an ability to immediately retry select messages in the queue.  For instance, if I have several messages for a certain campaign that are waiting for a retry, I may want to retry them all immediately.  The below example idea is borrowed from the existing kcli format
IE: kcli --endpoint http://127.0.0.1:8000 retry --campaign mytestcampaign --reason "waiting too long"
Where "retry" is the command that does not exist yet where it just pushes it up the queue to immediate retry.

Ideally, you could set --campaign --domain --tenant --everything

**Comment by wez** [comment]
You can do this with rebind: https://docs.kumomta.com/reference/kcli/rebind/
