### ISSUE TITLE
Add proxy logging to standard local logs

### ISSUE THREAD

**Issue by tommairs** [KumoCorp/kumomta#154]
When using a proxy, the proxy information is recorded in the system journal but not in the normal local logs.

It would be nice to have the proxy data logged in the same way other data is logged.

IE: `socks5_proxy_server: Some(54.218.75.124:5000), socks5_proxy_source_address: Some(172.31.27.74)`

Those and the similar HA Proxy fields should be available for local logging:
https://docs.kumomta.com/reference/kumo/configure_local_logs/#log-record

**Comment by wez** [comment]
I think this is really the same issue as:
* https://github.com/KumoCorp/kumomta/issues/40
