### ISSUE TITLE
Allow manual triggering of requeue_message

### ISSUE THREAD

**Issue by tommairs** [KumoCorp/kumomta#158]
There are times when an operator may want to have KumoMTA re-evaluate messages and requeue them based on new information.  
 - A campaign may have been assigned to the wrong queue and needs to be re-routed
 - IPs for a queue source may need to be reallocated, causing queue management issues.
 - You may want to dump an entire campaign or other identified mail stream to a queue with different throttle settings (or to null)

Ideally, the operator will have the ability to use requeue_messages exactly as documented, but have it triggered ad-hoc as opposed to waiting for a transient failure.

In practice, usage may look like this:

if msg:get_meta("campaign") == "Flash Sale - 10 minutes only" then
  manual_requeue_message ("queue","null")
end

OR
if msg:get_meta("campaign") == "Back to school" then
  manual_requeue_message ("tenant","customer_147")
end

Where the manual action would take place immediately on all queued messages (Scheduled and Ready) and the parameter to change will be one of :
    queue
    routing_domain
    tenant
    campaign

**Comment by wez** [comment]
You can do this with rebind and the --trigger-rebind-event flag

**Comment by wez** [comment]
https://docs.kumomta.com/reference/kcli/rebind/
