### ISSUE TITLE
Pool Assignment Re-Evaluation

### ISSUE THREAD

**Issue by MHillyer** [KumoCorp/kumomta#209]
If egress pool assignment doesn't work, users will assign to a suspended default, and they will need to command the MTA to re-assign the message to a new egress pool.

**Comment by wez** [comment]
It's worth pointing out that `rebind` doesn't really directly assign a pool, it just re-evaluates the scheduled queue, which in turn implies a change in egress pool

**Comment by wez** [comment]
[kcli rebind](https://docs.kumomta.com/reference/kcli/rebind/) docs are now in the reference manual
