### ISSUE TITLE
Option to partially reject emails

### ISSUE THREAD

**Issue by sevestar** [KumoCorp/kumomta#227]
Currently, when sending transactional emails using Kumo MTA with recipients in the "To," "CC," and "BCC" fields, rejecting an email due to exceeded sending quotas results in the entire email thread being rejected. We request the ability to reject only the specific email in the thread that exceeds the quota, without impacting the other recipients in the "To," "CC," and "BCC" fields. This enhancement would allow more precise control over email delivery and ensure compliance with sending limits without unnecessary rejection of valid emails within the same thread.

**Comment by MHillyer** [comment]
How would you expect this to work? When one message has multiple recipients it remains a single message, delivering only part of its recipients would be unpredictable behavior.

**Comment by wez** [comment]
Most ESPs send a single message per transaction to avoid this complexity.

From an SMTP perspective, the `To`, `Cc` and `Bcc` headers are irrelevant.  All that matters is the sequence of `RCPT TO` commands issued by the client in a given transaction.

If you want to limit the number of recipients in a transaction you can use https://docs.kumomta.com/reference/kumo/start_esmtp_listener/#max_recipients_per_message and kumomta will issue a response that will cause compliant SMTP clients to break up the batch and retry the excess.

If you want to do that dynamically, you can do so using the https://docs.kumomta.com/reference/events/smtp_server_mail_from/ and https://docs.kumomta.com/reference/events/smtp_server_rcpt_to/ event handlers to keep track of the current recipient list via the connection metadata and optionally reject recipients that exceed your limits during `RCPT TO`. 

If you have to receive the `DATA` before you can decide that want to accept the thread and prevent delivery to a subset of messages then you will need to handle this for yourself in your https://docs.kumomta.com/reference/events/smtp_server_message_received/ event handler.  The way to achieve this is to use whatever your limiting/quota logic is to decide whether a message should be relayed or not, and if not, route it to the `null` queue:

```lua
   msg:set_meta('queue', 'null')
```

It is your responsibility to do something to account for that; messages assigned to the `null` queue will silently disappear. If you want to notify someone about this, it is up to you to do that in an appropriate manner.
