### ISSUE TITLE
TLS Handshake Failed: NoCipherSuitesInCommon Error

### ISSUE THREAD

**Issue by arunkvinam** [KumoCorp/kumomta#235]
### What Operating System are you seeing this problem on?

Rocky8

### What Hardware is this system running?

Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              12
On-line CPU(s) list: 0-11
Thread(s) per core:  2
Core(s) per socket:  6
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
BIOS Vendor ID:      Intel(R) Corporation
CPU family:          6
Model:               158
Model name:          Intel(R) Xeon(R) E-2286G CPU @ 4.00GHz
BIOS Model name:     Intel(R) Xeon(R) E-2286G CPU @ 4.00GHz
Stepping:            10
CPU MHz:             4601.359
CPU max MHz:         4900.0000
CPU min MHz:         800.0000
BogoMIPS:            8016.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            12288K
NUMA node0 CPU(s):   0-11

### KumoMTA version

2024.05.23-11841789

### Did you try the latest release to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version that I tried

### Describe the bug

I encountered a TLS handshake failure while attempting to send an email using kumomta. The error log indicates that the peer is incompatible due to no common cipher suites. Below are the details of the error:
Jun 25 16:02:39  kumod[892323]: 2024-06-27T16:02:39.069254Z DEBUG  smtpsrv-8 run{socket=PollEvented { io: Some(TcpStream { addr: , peer: *.*.*.*:6100, fd: 19 }) }}:process: kumod::smtp_server: TLS handshake failed: peer is incompatible: NoCipherSuitesInCommon

### Configuration

Lua file

kumo.on('init', function()
	kumo.set_diagnostic_log_filter 'kumod=debug'
	kumo.start_esmtp_listener {
		listen = '0:2525',
		hostname = 'kumomta.domain.io'

	}

	kumo.start_esmtp_listener {
		listen = '0.0.0.0:587',
		hostname = 'kumomta.domain.io',
		tls_certificate = '/opt/kumomta/etc/ssl/kumomta.domain.io.cert.pem',
		tls_private_key = '/opt/kumomta/etc/ssl/kumomta.domain.io.key.pem',
		max_recipients_per_message = 10
	}
	kumo.start_http_listener {
		listen = '127.0.0.1:8000',
		hostname = 'kumomta.domain.io',
		use_tls = false,
		tls_certificate = '/opt/kumomta/etc/ssl/kumomta.domain.io.cert.pem',
		tls_private_key = '/opt/kumomta/etc/ssl/kumomta.domain.io.key.pem',
	}

	kumo.define_spool {
		name = 'data',
		path = '/var/spool/kumomta/data',
		kind = 'RocksDB',
	}

	kumo.define_spool {
		name = 'meta',
		path = '/var/spool/kumomta/meta',
		kind = 'RocksDB'
	}

	kumo.configure_local_logs {
		log_dir = '/var/log/kumomta',
		headers = { 'Subject', 'X-Tracking-Id' },
		meta = { 'received_from','tenant','received','domain','routing_domain' },
	}

	kumo.configure_bounce_classifier {
		files = {
			'/opt/kumomta/share/bounce_classifier/iana.toml',
		},
	}

	kumo.configure_log_hook {
		name = 'amqp',
		headers = { 'Subject', 'X-Tracking-Id' },
		meta = { 'received_from','tenant','received','domain','cid','pool_id','server_id' ,'email_domain','received_at','from_email','routing_domain'},

	}

end)

**Comment by wez** [comment]
The client is using a set of incompatible cipher suites.
You should either:

1. **Strongly Preferred**: upgrade your client to use a more modern TLS implementation and cipher suite,
2. or: disable TLS in the configuration of that client. Note that legacy cipher suites are generally broken/compromised and should not be used; they are generally equivalent to clear text anyway, so disabling TLS in that case is not a material reduction in the privacy of the connection.
