### ISSUE TITLE
Authentication-Results Header

### ISSUE THREAD

**Issue by MHillyer** [KumoCorp/kumomta#261]
Dependent on SPF/DKIM/DMARC checking.

As a receiver of mail, I want to ensure my incoming messages are properly authenticated, and I want to ensure that downstream systems know the outcome of our authentication checks.

The standard for this header is defined in RFC 7601: https://datatracker.ietf.org/doc/html/rfc7601

**Comment by wez** [comment]
We already do this for dkim verification, and have a helper for adding arbitrary additional results:
* https://docs.kumomta.com/reference/message/add_authentication_results/
*
