### ISSUE TITLE
Add logging for Outbound TLS

### ISSUE THREAD

**Issue by tommairs** [KumoCorp/kumomta#39]
We should add these logging items

The TLS version that was negotiated with the remote end during STARTTLS
The TLS cipher that was negotiated with the remote end during STARTTLS

**Comment by wez** [comment]
Game plan: extracting the tls ciphers/usage for an outbound session (inbound too, but that's less interesting to our target market at this time) and capturing that information into the delivery logs.

Layer-wise, SmtpClient https://github.com/KumoCorp/kumomta/blob/7b63f7d80d980848b90b44ba5f101c887c466065/crates/rfc5321/src/client.rs#L195 is the "class" that should expose the outgoing connection info.

https://github.com/KumoCorp/kumomta/blob/7b63f7d80d980848b90b44ba5f101c887c466065/crates/rfc5321/src/client.rs#L490 is where TLS is negotiated

I'd suggest adding a method that returns a TlsInformation struct that has version, cipher and maybe a reference to the certificate in it?

Then for the logging, adding optional fields to https://github.com/KumoCorp/kumomta/blob/7b63f7d80d980848b90b44ba5f101c887c466065/crates/kumo-log-types/src/lib.rs#L43 for the tls version and cipher

and populating them via https://github.com/KumoCorp/kumomta/blob/7b63f7d80d980848b90b44ba5f101c887c466065/crates/kumod/src/logging.rs#L369 when logging the results in https://github.com/KumoCorp/kumomta/blob/7b63f7d80d980848b90b44ba5f101c887c466065/crates/kumod/src/smtp_dispatcher.rs#L341

**Comment by wez** [comment]
This is now available for deliveries, but not receptions
