### ISSUE TITLE
KumoProxy - SOCKS5 Proxy

### ISSUE THREAD

**Issue by MHillyer** [KumoCorp/kumomta#45]
While HAProxy support is a good step toward our users being able to leverage more IPs than can typically be allocated on a single instance, it remains limited as a solution due to how it handles connection issues.

We will improve on the current functionality available via HAProxy by implementing a more tightly integrated proxy using SOCKS5.

Consider building off:
* https://github.com/dizda/fast-socks5
* https://github.com/ajmwagar/merino
* https://github.com/saiko-tech/mmproxy-rs/ (this has some more sophisticated piping/splicing that should have better throughput)

**Comment by wez** [comment]
I've put this into the main kumo packages. In the future I'll make separate packages, but it's a bit of a faff for right now.

Usage is very simple:

```console
$ proxy-server --help
KumoProxy SOCKS5 Proxy Server

Usage: proxy-server [OPTIONS]

Options:
      --listen <LISTEN>
      --timeout-seconds <TIMEOUT_SECONDS>  [default: 60]
  -h, --help
```

So:

```console
$ proxy-server --listen 10.0.0.1:1080
```
