### ISSUE TITLE
RFC 2549 Support

### ISSUE THREAD

**Issue by MHillyer** [KumoCorp/kumomta#48]
KumoMTA is for all use cases, which means having wide support for all RFCs pertaining to data transmission. 

Lack of RFC2549 support is a glaring omission in all other MTAs, whether commercial or Open Source.

**Comment by wez** [comment]
I think this got added to the backlog about 2 months too late to be feasible

**Comment by MHillyer** [comment]
I'm sorry you lost your testing infrastructure, I can procure you some new ones.
