### ISSUE TITLE
Automated Suspension of a pathway.

### ISSUE THREAD

**Issue by MHillyer** [KumoCorp/kumomta#51]
As a Deliverability Engineer, there are numerous responses I can encounter that are best addressed by suspending my traffic on a given pathway for a period of time.

One example of this is the common Yahoo TS04 error:

`421 4.7.0 [TSS04] Messages from 0.0.0.0 temporarily deferred due to user complaints - 4.16.55.1; see https://postmaster.yahooinc.com/error-codes`

When such an error is encountered, the MTA needs to stop sending over that IP to the Yahoo MX group for two hours, as per Yahoo's recommendation.

**Comment by wez** [comment]
https://docs.kumomta.com/reference/kumo.shaping/load/#traffic-shaping-automation-rules
