### ISSUE TITLE
Pattern Matching of Remote Responses

### ISSUE THREAD

**Issue by MHillyer** [KumoCorp/kumomta#52]
As a Deliverability Engineer, I need to be able to define the events I'm interested in automating, based on the response returned by the remote MTA.

For this to work, I need to be able to define the response string of interest using expressions, because remote servers can return customized responses that are personalized to the individual interaction.

For example, I may receive a response such as:

`451 4.2.0 68.69.14.27 Throttled - try again later. SyEWdGKFD38hOSyEbdIFU1 Please see [http://postmaster.comcast.net/smtp-error-codes.php#RL000002](http://postmaster.comcast.net/smtp-error-codes.php#RL000002%C2%A0)`

In this case, the random string is not of interest, and the IP address is specific to the individual connection. My real interest is in the initial IANA response code and the RL000002 category code.

**Comment by wez** [comment]
https://docs.kumomta.com/reference/kumo.shaping/load/#traffic-shaping-automation-rules supports using regex
