### ISSUE TITLE
Configuration of traffic shaping automation rules.

### ISSUE THREAD

**Issue by MHillyer** [KumoCorp/kumomta#53]
As a Deliverability Engineer, I need to be able to record the rules I want used for my traffic shaping automation.

I would like to know that I can start from a default set of rules that are updated by the community, but can then augment/replace existing rules with logic I have created from my own research and experience.

While I would like to be able to manage those rules through a UI that is either provided or developed myself, I typically expect that the rules do not change on a very regular basis and therefore am fine with manually editing a file with my rules contained in it.

I want to be able to define rules based on a site name that represents a rollup of all domains that deliver to the same MX servers, but also may need to explicitly define rules for a domain in spite of it being a member of a given site name.

For each rule, I want to be able to specify the response in question and one or more actions to take as a result of the response.

I should be able to leave comments in the rules file so that I can reference those comments in the future to determine the logic used by myself, my peers, or my predecessors.

**Comment by wez** [comment]
https://docs.kumomta.com/reference/kumo.shaping/load/#traffic-shaping-automation-rules
