### ISSUE TITLE
Automated adjustment of messages per hour.

### ISSUE THREAD

**Issue by MHillyer** [KumoCorp/kumomta#54]
As a Deliverability Engineer I have to handle responses from remote MTAs that indicate our server is sending too quickly.

For example:

`451 4.7.650 The mail server [x.xx.xx.xx] has been temporarily rate limited due to IP reputation. For e-mail delivery information, see https://postmaster.live.com (S843)[#.prod.protection.outlook.com]`

I need to throttle traffic down, wait an appropriate period of time to see if the response stops being returned, then try and throttle down again.

While there are ISP responses to say I need to throttle down, there are no anticipated responses to tell me to throttle up, so I either need to make the throttle down a temporary measure, or be able to define a cadence at which the server should attempt to throttle back up, likely based on age of the IP or time since the last throttle down response.

**Comment by wez** [comment]
See https://docs.kumomta.com/reference/kumo.shaping/load/#traffic-shaping-automation-rules
You can set a time-limited override for https://docs.kumomta.com/reference/kumo/make_egress_path/#max_message_rate
