### ISSUE TITLE
Need a switch to turn off Jinja templating with HTTP injections

### ISSUE THREAD

**Issue by tommairs** [KumoCorp/kumomta#58]
### What Operating System are you seeing this problem on?

NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

### What Hardware is this system running?

Standard D8lds v5 (8 vcpus, 16 GiB memory)

### KumoMTA version

kumod 2023.06.15-4cf2e65c

### Did you try the latest release to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version that I tried

### Describe the bug

A user needs the ability to disable Jinja when using API injections.  There are times when using % raw % around a body is not practical, but the content includes template markers that should NOT be expanded.

IE: sometimes {{ is just "{{"

### To Reproduce

add {{ in a body of a message but do not have it expanded.

### Configuration

N/A

**Comment by wez** [comment]
This is moderately tricky because of how entrenched the templating logic is in the code, and the frustrating lifetime associated with managing the compiled templates.

I think the workaround in the meantime is to pass in a `message` substitution in the request with the full text of the message body and set the content to `{{ message }}`.

**Comment by wez** [comment]
Closing because the raw block support in minijinja was resolved:
* https://github.com/KumoCorp/kumomta/issues/60
