### ISSUE TITLE
Using {% raw %} prevents Jinja substitutions but also malforms the email

### ISSUE THREAD

**Issue by tommairs** [KumoCorp/kumomta#60]
### What Operating System are you seeing this problem on?

NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

### What Hardware is this system running?

Standard D8lds v5 (8 vcpus, 16 GiB memory)

### KumoMTA version

kumod 2023.06.15-4cf2e65c

### Did you try the latest release to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version that I tried

### Describe the bug

Jinja templating on RFC822 strings — seems like {% raw %} correctly prevents processing of substitutions but also gets included in the output which makes the email malformed;

### To Reproduce

Create an HTTP API injection and wrap the content with {% raw %} tags to prevent any Jinja expansion.  The received message will include the tags but they should be stripped after processing.

### Configuration

N/A

**Comment by wez** [comment]
The `raw` and `endraw` syntax is supported in minijinja 1.0, but we are running `0.30`, so this is "expected" behavior.
We should update the docs to point to the correct version of minijinja.

**Comment by wez** [comment]
Seems like an issue with the underlying crate. I've opened https://github.com/mitsuhiko/minijinja/issues/305 to track this
