### ISSUE TITLE
Transient failures due to misbehaving peer with `OpportunisticInsecure` TLS

### ISSUE THREAD

**Issue by bendyer** [KumoCorp/kumomta#67]
### What Operating System are you seeing this problem on?

Rocky Linux 9

### What Hardware is this system running?

AWS hvm instance

### KumoMTA version

kumod 2023.06.19-ab80d4ca

### Did you try the latest release to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version that I tried

### Describe the bug

We're running with `enable_tls = 'OpportunisticInsecure'` in the `default` block in our `shaping.toml`, and occasionally getting seeing messages similar to the following:

```
kumod[1454]: 2023-06-20T05:04:09.918628Z DEBUG     localset-0 kumod::ready_queue: Error in Dispatcher::run for netX_X->(mfgw4|ocn-fc-r-01).ocn.ad.jp: TLS handshake failed with ResolvedAddress { name: "ocn-fc-r-01.ocn.ad.jp.", addr: 211.16.12.129 }:25: peer misbehaved: received unadvertised sig scheme RSA_PKCS1_SHA1 (consecutive_connection_failures=2)
```

It appears that this error is legitimate, in that the remote mailserver is indeed returning an unadvertised signature scheme, however with `OpportunisticInsecure` I think the system should fall back to unencrypted rather than failing the connection.

### Configuration

In `shaping.toml`:

```
["default"]
  replace_base = true
  max_deliveries_per_connection = 10
  enable_tls = 'OpportunisticInsecure'
  max_ready = 1000
  connection_limit  = 3
  connect_timeout = '60s'
  ehlo_timeout = '60s'
  mail_from_timeout = '60s'
  rcpt_to_timeout = '60s'
  data_timeout = '30s'
  rset_timeout = '30s'
  idle_timeout = '15s'
```

### Expected Behavior

`OpportunisticInsecure` should result in falling back to unencrypted communication regardless of the nature of the TLS failure

**Comment by wez** [comment]
I think this is a reasonable request for `OpportunisticInsecure`.
Specifically, we can change the behavior to treat any and all possible causes of a handshake error as a signal to proceed in clear text.
Being selective about the underlying cause of the handshake is a bit more involved and I'm not sure if there are any reasons that we'd want to exclude from this logic in this situation anyway.
