### ISSUE TITLE
Missing dkim key can block delivery

### ISSUE THREAD

**Issue by tommairs** [KumoCorp/kumomta#69]
### What Operating System are you seeing this problem on?

NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

### What Hardware is this system running?

Azure Standard D4lds v5 (4 vcpus, 8 GiB memory)

### KumoMTA version

kumod 2023.06.23-426225c7

### Did you try the latest release to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version that I tried

### Describe the bug

While using the dkim helper, defining a dkim signing key file that does not exist can block sending.  The system journal will report hundreds of these:
```Jun 23 22:21:07 Kubuntu-dev3 kumod[7872]: stack traceback:
Jun 23 22:21:07 Kubuntu-dev3 kumod[7872]:         [C]: in local 'poll'
Jun 23 22:21:07 Kubuntu-dev3 kumod[7872]:         [string "?"]:5: in main chunk
Jun 23 22:21:07 Kubuntu-dev3 kumod[7872]:         (...tail calls...)
Jun 23 22:21:07 Kubuntu-dev3 kumod[7872]:         /opt/kumomta/share/policy-extras/dkim_sign.lua:193: in upvalue 'do_dkim_sign'
Jun 23 22:21:07 Kubuntu-dev3 kumod[7872]:         /opt/kumomta/share/policy-extras/dkim_sign.lua:255: in upvalue 'dkim_signer'
Jun 23 22:21:07 Kubuntu-dev3 kumod[7872]:         [string "/opt/kumomta/etc/policy/init.lua"]:388: in function <[string "/opt/kumomta/etc/policy/init.lua"]:366>
Jun 23 22:21:07 Kubuntu-dev3 kumod[7872]: caused by: File("/opt/kumomta/etc/dkim/myexampledomain.com/dkimselector.key"): No such file or directory (os error 2)
Jun 23 22:21:08 Kubuntu-dev3 kumod[7872]: 2023-06-23T22:21:08.019195Z ERROR localset-2 run{socket=PollEvented { io: Some(TcpStream { addr: 127.0.0.1:587, peer: 127.0.0.1:35810, fd: 40 }) }}: kumod::smtp_server: Error in SmtpServer: callback error
```

### To Reproduce

Configure dkim to use a specific file, but no not actually create the file.

[domain.'myexampledomain.com']
  selector = 'dkimselector'
  algo = 'sha256'
  headers = [ 'From', 'To', 'Subject', 'Date', 'MIME-Version' ]
  filename = "/opt/kumomta/etc/dkim/thisDirectoryDoesNotExist/dkimselector.key"
  policy = "SignAlways"

### Configuration

See above

### Expected Behavior

I would have expected the dkim signer to try once, then fail with an error logged and move on.

**Comment by wez** [comment]
When the signer is invalid it will generate a `421 4.3.0 foo technical difficulties`.  This is by design: the intent is prevent mail from being relayed with a missing signature when the configuration calls for it to be signed, in order to protect/maintain reputation.

If your injector retries the message immediately, which is the case for traffic-gen, then you will see the same error repeated in the logs.

There are two paths through this:

1. You can wrap the signing stage of the policy in a pcall if you don't care about any dkim errors:

```lua
local signed, reason = pcall(dkim_signer, msg)
if not signed then
  print("Error signing: ", reason)
end
```

2. We can look at introducing a per-signature error policy to the dkim toml data file to allow ignoring problems on a per-signature basis, that is essentially a variation on the above but baked into the helper

**Comment by wez** [comment]
and/or option 3: is that we make it a permfail rejection rather than a tempfail, and/or make that an option in the data file

**Comment by tommairs** [comment]
After looking at this more closely, it seems to be an injector problem not a KumoMTA problem.  I'll withdraw the bug report and call this "resolved" and make a note about injector issues somewhere else.

**Comment by tommairs** [comment]
Closed as a non issue.  This is an injector problem.
