### ISSUE TITLE
Should allow wildcards in headers for logging

### ISSUE THREAD

**Issue by tommairs** [KumoCorp/kumomta#74]
### What Operating System are you seeing this problem on?

CBL-Mariner/Linux

### What Hardware is this system running?

Azure Standard VM

### KumoMTA version

kumod 2023.07.22-d4ae999a

### Did you try the latest release to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version that I tried

### Describe the bug

When defining a logging configuration, an operator should be able to define headers that include a wildcard.
IE: headers = {*} means record all headers ( could be scary huge and we may need to impose limits)
More importantly, they should be able to do something like:
headers = {'X-*'} or headers = {'Subject', 'Cust_*'}

This will enable users to capture all headers in a type; for instance if they want all "X-"Headers

``` 
 kumo.configure_local_logs {
    log_dir = '/var/log/kumomta',
    headers = { 'Subject', 'From', 'To', 'Date', 'X-*' },
    . . .
} 
```

### Configuration

  kumo.configure_local_logs {
    log_dir = '/var/log/kumomta',
    max_segment_duration = '5 minutes',
    headers = { 'Subject', 'X-Customer-ID','Sender_local', 'X-Tenant' },
    meta = {'Sender_local','tenant','campaign','queue'},

^^ Should be able to use a wildcard here.

**Comment by wez** [comment]
This is now implemented in `main`
