### ISSUE TITLE
Support/publish OpenAPI compliant HTTP API

### ISSUE THREAD

**Issue by wez** [KumoCorp/kumomta#96]
I was asked recently if we had an [OpenAPI spec](https://www.openapis.org/) for our API.
I hadn't heard of this before, but having one would allow tools such as [openapi-generator](https://github.com/OpenAPITools/openapi-generator) to take care of boilerplate and code generation for various different client/language environments.

This issue represents the effort of evaluating what it means to:
* Write a spec that encodes our current API
* How we can keep that spec synced up with the evolving code base
* Whether we might need to publish slightly different versions of existing endpoints to conform with OpenAPI
* Whether we can automatically extract that information and include it in our docs

**Comment by wez** [comment]
Options for maintainability are:
* [aide](https://docs.rs/aide/latest/aide/)
* [utoipa](https://github.com/juhaku/utoipa)

**Comment by wez** [comment]
Also, this closed issue in the axum repo is tracking but not tracking the work that is not happening but might happen in the future to offer first-class support for openapi in axum itself:
* https://github.com/tokio-rs/axum/issues/50

**Comment by wez** [comment]
Looking at:
* https://github.com/kanidm/kanidm/issues/2028

which is the equivalent of this issue but in someone else's project, they went with utoipa in their PR for this:
* https://github.com/kanidm/kanidm/pull/2175

**Comment by musjj** [comment]
Just curious, but what did you end up using?

**Comment by wez** [comment]
You can see from the commit activity above that we used utoipa.
My preference, were I to do this again today, would be to use dropshot, however, they were a little behind on hyper+rustls last time I looked, which would frustrate that effort. It's possible that they are up to date now though.
